# Generated by Django 2.2 on 2020-10-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
